### ISSUE TITLE
No module named 'models'

### ISSUE THREAD

**Issue by wuhongsheng** [opencv/opencv_zoo#105]
i try  excute  eval.py command out error

  File "/data1/opencv_zoo/tools/eval/eval.py", line 15, in <module>
    from models import MODELS

python /data1/opencv_zoo/tools/eval/eval.py -m sface -d lfw -dr  ../

**Comment by fengyuentau** [comment]
Hello, did you solve the problem? I guess you need to set the `PYTHONPATH` environment variable before running the evaluation command:

```shell
# in linux
export PYTHONPATH=${opencv_zoo} # replace ${opencv_zoo} with the absolute path in your file system
```
