### ISSUE TITLE
DNN model used in SFace feature extractor?

### ISSUE THREAD

**Issue by xperroni** [opencv/opencv_zoo#107]
The original implementation of the SFace feature extractor integrated to OpenCV can be instantiated from three different DNN models — ResNet50, Resnet101 and MobileFaceNet. It would be useful for research purposes if the model actually used was documented somewhere.

**Comment by fengyuentau** [comment]
Thank you for the suggestion. Models in this zoo or integrated to OpenCV are usually considered as deploy-ready. To serve this purpose, the model itself should be lightweight enough, e.g. mobilenet or other lightweight base models is used for feature extraction. Anyway, it is a good suggestion to document the model architecture. Could you help us to improve the documentation for SFace by submitting a pull request?

**Comment by fengyuentau** [comment]
> confirm whether it's actually using MobileFaceNet

@zhongyy Could you take a look at this issue?

**Comment by zhongyy** [comment]
> mobilenet

Hi, Yuantao. I have told Helio by email before. @xperroni  The OpenCV version is based on MobileNet.

**Comment by fengyuentau** [comment]
Hello @xperroni , do you plan to create a pull request for the documentation update if possible?

**Comment by xperroni** [comment]
Pull request submitted, see here: #121
