### ISSUE TITLE
YuNet incorrrect face landmarks

### ISSUE THREAD

**Issue by yusufpraditya** [opencv/opencv_zoo#116]
when the face is very close to the camera, it gives incorrect landmarks. here is the screenshot: [https://ibb.co/VgttHnS](https://ibb.co/VgttHnS) 

here is the correct one: [https://ibb.co/vZwdTW0](https://ibb.co/vZwdTW0)

it affects SFace's alignCrop and makes distance between two face features below threshold

**Comment by fengyuentau** [comment]
This is limited by the training data and the training scheme. I cannot tell exactly the scale of your example image, but YuNet is trained to detect faces of pixels between around 10x10 to 300x300. Note that this is the face size, not the size of the whole image.

**Comment by yusufpraditya** [comment]
it occurs above 150px face size. tried using different type of webcam and still gives incorrect landmark at bigger face size. btw im using raspberry pi 4.  but strangely i dont find it incorrect landmarks using my laptop (thinkpad x230).

**Comment by fengyuentau** [comment]
I think you need to somehow control the face size on your Raspberry PI 4 deployment. By the way, did you do the same test on your laptop using the same webcam and testing with the faces above 150 pixels?

**Comment by yusufpraditya** [comment]
> I think you need to somehow control the face size on your Raspberry PI 4 deployment. By the way, did you do the same test on your laptop using the same webcam and testing with the faces above 150 pixels?

it turns out that the model used on the raspberry pi is the quantized version while on the laptop is not. tried using quantized on laptop and gives incorrect landmarks. i think the problem is solved..

**Comment by fengyuentau** [comment]
Okay, thanks for the feedback. It turns out the quantized model needs to be optimized then.
