### ISSUE TITLE
Which dataset to train model Sface onnx

### ISSUE THREAD

**Issue by trantrungpixta** [opencv/opencv_zoo#124]
Hi there,

I'm trying Sface. When I returned to the source code to [train Sface](https://github.com/zhongyy/SFace), I found many versions of the training dataset: CASIA-WebFace, VGGFace2, and MS1MV2. So which training dataset for the onnx Sface in the model zoo of OpenCV?

**Comment by fengyuentau** [comment]
@zhongyy Could you take a look at the problem if possible?

**Comment by TrungThanhTran** [comment]
Could you please answer.

**Comment by trantrungpixta** [comment]
@fengyuentau could you please answer?

**Comment by fengyuentau** [comment]
@trantrungpixta No, I am not familiar with the details on training SFace. You could either wait for its author's reply, or look into the paper or source code to find the answer.

**Comment by trantrungpixta** [comment]
@zhongyy could u please take a look?

**Comment by fengyuentau** [comment]
I suggest you send emails to ask the author directly and seek clues from the paper. Close for no progression.
