### ISSUE TITLE
extra key for `crnn` model in eval script

### ISSUE THREAD

**Issue by labeeb-7z** [opencv/opencv_zoo#125]
Running the evaluation script for text_recognition CRNN model as described [here](https://github.com/opencv/opencv_zoo/tree/master/tools/eval#ICDAR2003 ) , gives the following error : 

`TypeError: CRNN.__init__() got an unexpected keyword argument 'charsetPath'`

The CRNN constructor does not expect a `charsetPath` argument, so removing it fixes the issue.

Can I submit a PR for this @fengyuentau ?

**Comment by fengyuentau** [comment]
Yes, feel free to contribute!

BTW, this `charsetPath` is removed since https://github.com/opencv/opencv_zoo/pull/123.
