### ISSUE TITLE
 Integrate u2net into model zoo

### ISSUE THREAD

**Issue by jsxyhelu** [opencv/opencv_zoo#13]
U2net is very typical in image segmentation. It is the implementation of pytorch. I think it is valuable to convert it to onnx and call opencv directly. I don't know whether the up master has considered it. Thank you！

u2net在图像分割这块已经非常典型，本身是pytorch的实现，我认为转换为onnx并且让opencv直接调用是有价值的工作，不知道up主是否有考虑做下，谢谢！

**Comment by fengyuentau** [comment]
Okay, I will try to add it in the following week.

**Comment by fengyuentau** [comment]
@jsxyhelu can u provide a link to the paper or github repo of u2net?

**Comment by fengyuentau** [comment]
For the human-segmentation u2net, I have create scripts to port u2net to ONNX (`u2net_human_seg-2onnx.py`) and perform inference using OpenCV DNN (`u2net_huam_seg-onnx-opencv.py`). Get these scripts: https://github.com/fengyuentau/U-2-Net/tree/onnx_export.

However, the model itself is too large (168MB) to put into our zoo. The size of models in this zoo should be lower than 100MB.

**Comment by jsxyhelu** [comment]
that is great,thanks!
