### ISSUE TITLE
add support for c++? like add the demo of c++.

### ISSUE THREAD

**Issue by kekxv** [opencv/opencv_zoo#132]
add support for c++? like add the demo of c++.

**Comment by fengyuentau** [comment]
It could be interesting. Currently our demos are focusing on easy-to-use and work-out-of-the-box. Demos in C++ could be helpful in some cases but not the first priority to consider.

**Comment by kekxv** [comment]
> It could be interesting. Currently our demos are focusing on easy-to-use and work-out-of-the-box. Demos in C++ could be helpful in some cases but not the first priority to consider.

python is too concise, and it is difficult to convert to other languages.

**Comment by fengyuentau** [comment]
After an internal discussion on this feature, we agree that C++ demos can be added but they should be clean and simple enough to show how to run inference and get the expected output. I will create an issue tracking the status of C++ demos and I will provide the first C++ demo as soon as possible.

**Comment by fengyuentau** [comment]
The first C++ demo is here: https://github.com/opencv/opencv_zoo/pull/138. Feel free to review.

**Comment by fengyuentau** [comment]
Task tracker for adding C++ demos: https://github.com/opencv/opencv_zoo/issues/135.
