### ISSUE TITLE
The match function of SFace in C++ returns incorrect results

### ISSUE THREAD

**Issue by zhaodianbo** [opencv/opencv_zoo#155]
I tested the face comparison function of SFace on my Mac M1 machine, and when I tested it using face_recognition_sface/demo.py, it returned the correct results. However, when I compiled and tested it using C++ or Go, the match function returned incorrect results. After analysis, I suspect that the normalization result in the match function is incorrect. Is there a solution to this problem?

here is c++ code：
```
int main(){
    double ret=SFace_Test("face_detection_yunet_2022mar.onnx","face_recognition_sface_2021dec.onnx");
    printf("ret=%.10lf\n",ret);

    // images of same person. c++ ret=0.9999999593      if use demo.py it returns 0.9504736052325597
    // images of different person. c++ ret=0.9999998840.  if use demo.py it returns 0.026877811336817103
    // printf("ret=%.10f\n",ret);  use '%.10f'  return same result
}

double SFace_Test(const char* detect_model,const char* recog_model){

    cv::Mat image1 = cv::imread("./img/1.jpg");
    cv::Mat image2 = cv::imread("./img/3.jpg");

    cv::Ptr<cv::FaceDetectorYN> faceDetector = cv::FaceDetectorYN::create(detect_model, "", cv::Size(150, 150));
    cv::Ptr<cv::FaceRecognizerSF> faceRecognizer = cv::FaceRecognizerSF::create(recog_model, "");

    cv::Mat feature1=getFaceFeature(faceDetector,faceRecognizer,image1);
    cv::Mat feature2=getFaceFeature(faceDetector,faceRecognizer,image2);
    return faceRecognizer->match(feature1, feature2, cv::FaceRecognizerSF::DisType::FR_COSINE);
}

cv::Mat getFaceFeature( cv::Ptr<cv::FaceDetectorYN> faceDetector , cv::Ptr<cv::FaceRecognizerSF> faceRecognizer,cv::Mat image){
     faceDetector->setInputSize(image.size());
     cv::Mat faces;
     faceDetector->detect(image, faces);
     cv::Mat aligned_face;
     faceRecognizer->alignCrop(image, faces.row(0), aligned_face);
     cv::Mat feature;
     faceRecognizer->feature(aligned_face, feature);
     return feature;
 }

```
 g++ -v
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix

opencv version 4.7.0
Python 3.11.3

CXX = g++
CXXFLAGS +=   -std=c++11  -v -c -Wall $(shell pkg-config --cflags opencv4) 
LDFLAGS += -lstdc++ $(shell pkg-config --libs opencv4)

**Comment by fengyuentau** [comment]
Python's API (match) is actually calling the C++ implementation. So that must be something wrong in your code.

---

> `printf("ret=%.10lf\n",ret);`

You dont need `l` to print a double when using `printf`. See a duplicate here: https://github.com/opencv/opencv_zoo/issues/140#issuecomment-1457769884

**Comment by zhaodianbo** [comment]
printf("ret=%.10lf\n",ret);  is not working！ result is same as %.10f
I also tested use Go, result is also wrong

**Comment by zhaodianbo** [comment]
Actually, I first tested with Go code and found that the comparison results were incorrect. That's why I used C++ code to test it. However, I found that the results were inconsistent with Python's results. The code is very simple, which confuses me.

**Comment by fengyuentau** [comment]
```.diff
-    cv::Mat feature1=getFaceFeature(faceDetector,faceRecognizer,image1);
-    cv::Mat feature2=getFaceFeature(faceDetector,faceRecognizer,image2);
+    cv::Mat feature1=getFaceFeature(faceDetector,faceRecognizer,image1).clone();
+    cv::Mat feature1=getFaceFeature(faceDetector,faceRecognizer,image1).clone();
```

Classic C++ misuse.
1. Your `feature` is extracted in a function, so it is a local variable.
2. When you call `getFaceFeature` the first time, feature is extracted and then returned, resulting in a **shallow copy** to `feature1`. In my changes above, `.clone()` makes it a deep copy.
3. When you call `getFaceFeature` the second time, local variable `feature` is reused to save memory, and it is overwritten by the features of image2. This changes the values in `feature1` as well due to **shallow copy**.
4. So you get `feature1` and `feature2`, both have exact same values, resulting in very high cosine score (because they are the same one!).

**Comment by zhaodianbo** [comment]
Thank you very much, the correct value was returned after using the clone() method. I will continue testing in the future, thx！
