### ISSUE TITLE
bug in class PPHumanSeg   

### ISSUE THREAD

**Issue by anyfig** [opencv/opencv_zoo#162]
python:3.8.8
opencv:4.7.0.72

error: (-215:Assertion failed) _FX_WINO_IBLOCK == 3 && _FX_WINO_KBLOCK == 4 in function 'cv::dnn::_fx_winograd_accum_f32'
fix: add `self._model.enableWinograd(False)` in class PPHumanSeg

**Comment by fengyuentau** [comment]
> error: (-215:Assertion failed) _FX_WINO_IBLOCK == 3 && _FX_WINO_KBLOCK == 4 in function 
> 'cv::dnn::_fx_winograd_accum_f32'
> fix: add self._model.enableWinograd(False) in class PPHumanSeg

@zihaomu Please take a look at this problem.

**Comment by zihaomu** [comment]
Hi @anyfig, the 4.7 release has a bug of `Winograd` on AVX-only platform. Related to https://github.com/opencv/opencv/issues/23072.

For now, you can try the lateset `opencv-python-rolling` version, it should fix your issue.

```py
pip uninstall opencv-python
pip install opencv-python-rolling==4.7.0.20230513
```

**Comment by fengyuentau** [comment]
Feel free to reopen this issue if you still have questions.

**Comment by fengyuentau** [comment]
Feel free to reopen this issue if you still have questions.
