### ISSUE TITLE
Layer with requested id=-1 not found in function 'getLayerData' when using yunet face detection

### ISSUE THREAD

**Issue by erfansafaie** [opencv/opencv_zoo#172]
I'm trying to face detection using yunet by cv2. I load "face_detection_yunet_2023mar.onnx" by cv2.FaceDetectorYN_create and initiate with fixed size image(320,320). when I load an image and detect I faced with this error:

    _, faces = face_detector.detect(img)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/dnn/src/net_impl.cpp:275: error: (-204:Requested object was not found) Layer with requested id=-1 not found in function 'getLayerData'

Ubuntu 20.04
python 3.8.10
opencv 4.7.0

how can I fix this issue?? anyone has faced with this error??

**Comment by fengyuentau** [comment]
`YuNet` here in the zoo has been upgraded to match the upcoming OpenCV 4.8.0 release. If you are using 4.7.0 or below, you need to do a checkout back to before the model was upgraded:

```
git checkout 7e062e54cf5410c09b795ff71b4a255e58498c79
```

Also you can build the latest OpenCV to try out the upgraded version for now.

**Comment by erfansafaie** [comment]
Where we can clone and build upgraded opencv version(4.8.0)?

**Comment by fengyuentau** [comment]
You can install the weekly build using `pip install opencv-python-rolling<5.0`.

**Comment by erfansafaie** [comment]
> You can install the weekly build using `pip install opencv-python-rolling<5.0`.

Other method like build from source is available for 4.8.0 version??

**Comment by fengyuentau** [comment]
> Other methods like build from source is available for 4.8.0 version??

Sure, clone the latest OpenCV and build from source:

```shell
git clone https://github.com/opencv/opencv.git
cmake -B build-opencv -S opencv
cmake --build build-opencv --target install -j8
```

**Comment by erfansafaie** [comment]
> > Other methods like build from source is available for 4.8.0 version??
> 
> Sure, clone the latest OpenCV and build from source:
> 
> ```shell
> git clone https://github.com/opencv/opencv.git
> cmake -B build-opencv -S opencv
> cmake --build build-opencv --target install -j8
> ```

I know

**Comment by fengyuentau** [comment]
> I know how build but it's 4.7.0 version! Can access to 4.8.0??

4.8.0 is not yet released but basically the code that you now clone is what 4.8.0 looks like.

**Comment by fengyuentau** [comment]
Hello, `4.8.0` has been released, feel free to have a try.

**Comment by Nadia-Mas** [comment]
You can clone the last version of openCV by pasting this piece of code in your cmd:

git clone https://github.com/opencv/opencv.git
cmake -B build-opencv -S opencv
cmake --build build-opencv --target install -j8
