### ISSUE TITLE
face_recognition_sface_2021dec_int8.onnx may be have something wrong.

### ISSUE THREAD

**Issue by 12341234-yangboran** [opencv/opencv_zoo#189]
face_recognition_sface_2021dec_int8.onnx may be have something wrong.
I use images of two people，but faceRecognizerSF.match result is 0.999999

**Comment by 12341234-yangboran** [comment]
`// 3.读取图片
        Mat imageA = Imgcodecs.imread("C:/Users/y1793/Desktop/30e480f71265744ba45878e0b94f370.jpg");
        Mat imageB = Imgcodecs.imread("C:/Users/y1793/Desktop/68c82edc82763f930777786580de935.jpg");

        Imgproc.resize(imageA, imageA, new Size(imageA.width()/3, imageA.width()/3));
        Imgproc.resize(imageB, imageB, new Size(imageB.width()/3, imageB.width()/3));

        // 4.人脸识别
        FaceDetectorYN faceDetectorYN = FaceDetectorYN.create("C:/Users/y1793/Downloads/face_detection_yunet_2022mar.onnx", "", new Size(), score_thresh, nms_thresh, top_k);
        MatOfRect faceA = new MatOfRect();
        faceDetectorYN.setInputSize(imageA.size());
        faceDetectorYN.detect(imageA, faceA);
        MatOfRect faceB = new MatOfRect();
        faceDetectorYN.setInputSize(imageB.size());
        faceDetectorYN.detect(imageB, faceB);

        for (int i = 0; i < faceA.height(); i++) {
            // 画人脸框
            Imgproc.rectangle(imageA, new Rect((int) (faceA.get(i, 0)[0]), (int) (faceA.get(i, 1)[0]), (int) (faceA.get(i, 2)[0]), (int) (faceA.get(i, 3)[0])), new Scalar(0, 255, 0), 2);
            // 画关键点
            Imgproc.circle(imageA, new Point(faceA.get(i, 4)[0], faceA.get(i, 5)[0]), 2, new Scalar(255, 0, 0), 2);
            Imgproc.circle(imageA, new Point(faceA.get(i, 6)[0], faceA.get(i, 7)[0]), 2, new Scalar(0, 0, 255), 2);
            Imgproc.circle(imageA, new Point(faceA.get(i, 8)[0], faceA.get(i, 9)[0]), 2, new Scalar(0, 255, 0), 2);
            Imgproc.circle(imageA, new Point(faceA.get(i, 10)[0], faceA.get(i, 11)[0]), 2, new Scalar(255, 0, 255), 2);
            Imgproc.circle(imageA, new Point(faceA.get(i, 12)[0], faceA.get(i, 13)[0]), 2, new Scalar(0, 255, 255), 2);
            Imgcodecs.imwrite("C:/Users/y1793/Desktop/imageA.jpg", imageA);
        }

        for (int i = 0; i < faceB.height(); i++) {
            // 画人脸框
            Imgproc.rectangle(imageB, new Rect((int) (faceB.get(i, 0)[0]), (int) (faceB.get(i, 1)[0]), (int) (faceB.get(i, 2)[0]), (int) (faceB.get(i, 3)[0])), new Scalar(0, 255, 0), 2);
            // 画关键点
            Imgproc.circle(imageB, new Point(faceB.get(i, 4)[0], faceB.get(i, 5)[0]), 2, new Scalar(255, 0, 0), 2);
            Imgproc.circle(imageB, new Point(faceB.get(i, 6)[0], faceB.get(i, 7)[0]), 2, new Scalar(0, 0, 255), 2);
            Imgproc.circle(imageB, new Point(faceB.get(i, 8)[0], faceB.get(i, 9)[0]), 2, new Scalar(0, 255, 0), 2);
            Imgproc.circle(imageB, new Point(faceB.get(i, 10)[0], faceB.get(i, 11)[0]), 2, new Scalar(255, 0, 255), 2);
            Imgproc.circle(imageB, new Point(faceB.get(i, 12)[0], faceB.get(i, 13)[0]), 2, new Scalar(0, 255, 255), 2);
            Imgcodecs.imwrite("C:/Users/y1793/Desktop/imageB.jpg", imageB);
        }

        // 5.人脸预处理
        FaceRecognizerSF faceRecognizerSF = FaceRecognizerSF.create("C:/Users/y1793/Downloads/face_recognition_sface_2021dec_int8.onnx", "");
        Mat alignFaceA = new Mat();
        faceRecognizerSF.alignCrop(imageA, faceA, alignFaceA);
        Mat alignFaceB = new Mat();
        faceRecognizerSF.alignCrop(imageB, faceB, alignFaceB);
        Imgcodecs.imwrite("C:/Users/y1793/Desktop/alignFaceA.jpg", alignFaceA);
        Imgcodecs.imwrite("C:/Users/y1793/Desktop/alignFaceB.jpg", alignFaceB);

        // 6.人脸特征提取
        MatOfRect featureA = new MatOfRect();
        faceRecognizerSF.feature(alignFaceA, featureA);
        MatOfRect featureB = new MatOfRect();
        faceRecognizerSF.feature(alignFaceB, featureB);

        // 7.人脸识别 余弦相似度
        double match1 = faceRecognizerSF.match(featureA, featureB, FaceRecognizerSF.FR_COSINE);`

**Comment by WanliZhong** [comment]
Hi @12341234-yangboran , it's not a bug or something wrong. It's because the value match return is not a score. You need to compare this value with a threshold like OpenCV zoo show below.
![image](https://github.com/opencv/opencv_zoo/assets/49567307/2495e5ad-cbb4-49d3-a72b-eb41d5b203d5)

**Comment by 12341234-yangboran** [comment]
Could i use the face_detection_yunet_2022mar.onnx and face_recognition_sface_2021dec_int8.onnx together?

**Comment by 12341234-yangboran** [comment]
Could i use the face_detection_yunet_2022mar.onnx and face_recognition_sface_2021dec_int8.onnx together?

**Comment by WanliZhong** [comment]
@12341234-yangboran `*_int8.onnx` model is used for some specific platform and the inference time will be much less, but accuracy may loss. If your platform doesn't support speed up int8 calculation, I suggest you use the model without int8 suffix version.

**Comment by 12341234-yangboran** [comment]
![image](https://github.com/opencv/opencv_zoo/assets/74187378/82c3e36e-d9a4-4dca-a13c-ffd7a08a69e4)
can i get the file in this way

**Comment by WanliZhong** [comment]
@12341234-yangboran I think you can download file in this way.

**Comment by denis-shienkov** [comment]
Hi. I have same issue. In my case the `match` also returns about `0.9999` for FR_COSINE, and about '0.000` for FR_NORM_L2... 

I use OpenCV  4.8.0 running on Windows OS, and your recognition model `face_recognition_sface_2021dec.onnx`..

I'm sure, that I use two different aligned images... so, something somewhere is wrong.

**Comment by denis-shienkov** [comment]
Ahh.. sorry... seems to need to call clone(), clone() clone() everywhere ))))
