### ISSUE TITLE
YuNet ONNX input & output model processing

### ISSUE THREAD

**Issue by rh-id** [opencv/opencv_zoo#192]
Hi, Thanks for great NN model.

I'm currently using Java and using the raw model https://github.com/opencv/opencv_zoo/blob/main/models/face_detection_yunet/face_detection_yunet_2023mar.onnx

I do not use openCV library but planning to use the model directly and code the input and output process.

Currently I'm at lost because I couldn't find explanation or documentation on how to perform preprocess and post-process.

Base on the model input output visualization : https://netron.app/?url=https://github.com/opencv/opencv_zoo/blob/main/models/face_detection_yunet/face_detection_yunet_2023mar.onnx

From the visualization I assume the input will be RGB image with size 640x640.
I can't figured what is cls_8/16/32, obj_8/16/32, bbox_8/16/32, kps_8/16/32 and how to massage it into output.

**Comment by fengyuentau** [comment]
Pre-processing and post-processing are wrapped in C++: https://github.com/opencv/opencv/blob/b8e3bc9dd866b028e33b769e3c0992fc2b55a660/modules/objdetect/src/face_detect.cpp#L97-L121

**Comment by rh-id** [comment]
Hi @fengyuentau thanks for the pointer

**Comment by rh-id** [comment]
Hi @fengyuentau just additional info, I decided to use OpenCV instead, and here is the [examples](https://github.com/rh-id/a-jarwis/tree/master/ml-engine%2Fsrc%2Fmain%2Fjava%2Fm%2Fco%2Frh%2Fid%2Fa_jarwis%2Fml_engine%2Fprovider%2Fcomponent)

just in case other people wanted example in java or android.

many thanks.
