### ISSUE TITLE
License Plate Detection Model

### ISSUE THREAD

**Issue by rh-id** [opencv/opencv_zoo#196]
Hi, Is it possible to train the existing license plate model ? If yes any guide for doing this transfer learning?

**Comment by fengyuentau** [comment]
Hello,

as far as I known, this model is trained on top of https://github.com/ShiqiYu/libfacedetection.train. Some training settings are changed, and training data is changed for sure. Unfortunately the author does not open source the modified training programe.

**Comment by rh-id** [comment]
Hi, ok thanks for the reply
