### ISSUE TITLE
error of FaceDetectorYN

### ISSUE THREAD

**Issue by 12341234-yangboran** [opencv/opencv_zoo#200]
[ERROR:0@0.752] global C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\net_impl.cpp (1171) cv::dnn::dnn4_v20220524::Net::Impl::getLayerShapesRecursively OPENCV/DNN: [Eltwise]:(onnx_node!Add_44): getMemoryShapes() throws exception. inputs=2 outputs=1/1 blobs=0
[ERROR:0@0.752] global C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\net_impl.cpp (1174) cv::dnn::dnn4_v20220524::Net::Impl::getLayerShapesRecursively     input[0] = [ 1 64 14 21 ]
[ERROR:0@0.752] global C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\net_impl.cpp (1174) cv::dnn::dnn4_v20220524::Net::Impl::getLayerShapesRecursively     input[1] = [ 1 64 14 20 ]
[ERROR:0@0.752] global C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\net_impl.cpp (1178) cv::dnn::dnn4_v20220524::Net::Impl::getLayerShapesRecursively     output[0] = [ 1 64 14 21 ]
[ERROR:0@0.752] global C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\net_impl.cpp (1184) cv::dnn::dnn4_v20220524::Net::Impl::getLayerShapesRecursively Exception message: OpenCV(4.6.0) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\layers\eltwise_layer.cpp:251: error: (-215:Assertion failed) inputs[vecIdx][j] == inputs[i][j] in function 'cv::dnn::EltwiseLayerImpl::getMemoryShapes'

**Comment by 12341234-yangboran** [comment]
model:face_detection_yunet_2023mar.onnx
opencv:4.8.0

**Comment by fengyuentau** [comment]
Could you share your input image or at least its size?

**Comment by 12341234-yangboran** [comment]
800x800

**Comment by 12341234-yangboran** [comment]
Not found the question in other verion
