### ISSUE TITLE
Neural Style Transfer OpenCV

### ISSUE THREAD

**Issue by rh-id** [opencv/opencv_zoo#201]
Hi, I'm referring to this tutorial https://docs.opencv.org/4.8.0/d7/d2d/tutorial_js_style_transfer.html

Would like to ask few things:
1. Is there any Java tutorial? I can't seem to find it, if yes please help provide if possible
2. In that tutorial it gave the torch model to download (example: https://cs.stanford.edu/people/jcjohns/fast-neural-style/models//instance_norm/candy.t7), this link seemed to be hosted at the university and from private share folder? what is the license for this model? Apache License 2 or BSD as stated at OpenCV website https://opencv.org/license/  ? or is it something else?
3. Are there any quantize models? can't seemed to find any in this repository.

**Comment by fengyuentau** [comment]
This model and tutorial are from a long time ago. I would suggest you look for another newer model. This model is not hosted here, therefore I could not provide any details on it.
