### ISSUE TITLE
FaceRecognizerSF.match result of FR_COSINE is Cosine Distance or Cosine Similarity

### ISSUE THREAD

**Issue by 12341234-yangboran** [opencv/opencv_zoo#202]
Could you tell me the FaceRecognizerSF.match result of FR_COSINE is Cosine Distance or Cosine Similarity?

**Comment by 12341234-yangboran** [comment]
The cosine distance is one minus the cosine similarity

**Comment by fengyuentau** [comment]
There is no cosine distance. Read the code before asking questions: https://github.com/opencv/opencv/blob/c9a4775d49202538ffa40fc147b502049a2ae93c/modules/objdetect/src/face_recognize.cpp#L49-L63
