### ISSUE TITLE
更新face_detection_yunet_2023mar.onnx后，原来检查出人像的图片，现在不能检查了

### ISSUE THREAD

**Issue by bestlee666** [opencv/opencv_zoo#206]
更新face_detection_yunet_2023mar.onnx后，原来检查出人像的图片，现在不能检查了，又遇到类似问题吗？

**Comment by bestlee666** [comment]
<img width="583" alt="baseface2" src="https://github.com/opencv/opencv_zoo/assets/143471781/968eb89d-e112-4319-ab87-eb1e7cc36db7">

**Comment by fengyuentau** [comment]
这是有可能发生的。我看了一下你的图片超过1000x1000的像素，那么图中的人脸估计都有500x500了。这个尺寸原本就超出这个模型的检测范围，检测的效果就不能得到保证了。

我把你的图片宽高都resize到原来的一半，这样人脸就检测出来了。

![image](https://github.com/opencv/opencv_zoo/assets/17219438/3af54fe8-04db-4a17-8159-853d96de09ca)

**Comment by bestlee666** [comment]
感谢这么快收到反馈，还发现2个人脸问题


我的环境，mac m2, opencv 4.8，float score_threshold=0.9f, float nms_threshold=0.3f,


数据见附件


1、360k_badcase.zip ，有部分头像时 比较清晰的，但也检查不到人脸，这是什么原因？



2、我这发现多个类似 yangyin8.jpg的情况，照片本身不大，人脸大小也在500*500内，仍检查不到人脸， 但单独截取人像部分 另存图片时， 却能检查出人脸，


3、我这发现多个类似&nbsp;&nbsp;bozhi44.jpg的情况，人脸有点偏 ，感觉应该能检查出了，能发优化下模型？






                       
原始邮件
                       
                     

发件人："Yuantao Feng"< ***@***.*** &gt;;

发件时间：2023/9/1 13:06

收件人："opencv/opencv_zoo"< ***@***.*** &gt;;

抄送人："bestlee666"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [opencv/opencv_zoo] 更新face_detection_yunet_2023mar.onnx后，原来检查出人像的图片，现在不能检查了 (Issue #206)




 
这是有可能发生的。我看了一下你的图片超过1000x1000的像素，那么图中的人脸估计都有500x500了。这个尺寸原本就超出这个模型的检测范围，检测的效果就不能得到保证了。
 
我把你的图片宽高都resize到原来的一半，这样人脸就检测出来了。

**Comment by fengyuentau** [comment]
我这里看不到附件，请在这个issue下上传或者提供网盘链接。

**Comment by fengyuentau** [comment]
请问问题解决了吗？

**Comment by bestlee666** [comment]
已解决，感谢您的支持，给力






                       
原始邮件
                       
                     

发件人："Yuantao Feng"< ***@***.*** &gt;;

发件时间：2023/9/13 10:20

收件人："opencv/opencv_zoo"< ***@***.*** &gt;;

抄送人："bestlee666"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [opencv/opencv_zoo] 更新face_detection_yunet_2023mar.onnx后，原来检查出人像的图片，现在不能检查了 (Issue #206)




 
请问问题解决了吗？
