### ISSUE TITLE
Can I run the onnx model as a batch process?

### ISSUE THREAD

**Issue by hopeux** [opencv/opencv_zoo#207]
I am trying to run the Onnx model as batch, but I cannot change the input_shape variable of the model. For this, I followed the steps in the link https://onnxruntime.ai/docs/tutorials/mobile/helpers/make-dynamic-shape-fixed.html.

Apart from this, I could not access any raw version of the model. If it is available, how can I reach it? If it is not available, where can I find the information necessary to train the model?

**Comment by fengyuentau** [comment]
1. You can use onnxsim to change the batch, https://github.com/daquexian/onnx-simplifier
2. We provide reference links to the original repository if possible. Go to those repos and find how to train the model.

**Comment by fengyuentau** [comment]
Close for now. Feel free to reopen if you still have questions.
