### ISSUE TITLE
objThreshold parameter not used in yolox

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv_zoo#208]
in yolox 
https://github.com/opencv/opencv_zoo/blob/05fe0a4d797ad31848872f77e7ba8511bbaeb70f/models/object_detection_yolox/demo.py#L103
parameter  objThreshold is not used in model
https://github.com/opencv/opencv_zoo/blob/05fe0a4d797ad31848872f77e7ba8511bbaeb70f/models/object_detection_yolox/yolox.py#L14

and of course in cpp code too...

**Comment by fengyuentau** [comment]
I think, we can use it to filter out non-object boxes in these piece of code:

https://github.com/opencv/opencv_zoo/blob/05fe0a4d797ad31848872f77e7ba8511bbaeb70f/models/object_detection_yolox/yolox.py#L59-L62
