### ISSUE TITLE
K-best BB VitTracker (feature/Question)

### ISSUE THREAD

**Issue by arielkantorovich** [opencv/opencv_zoo#218]
Hi,
I would be happy to know if I could get from `model.infer(frame)` the best K?

**Comment by fengyuentau** [comment]
You need to modify from source code to get top-k bbox. Current the API is set to get the best one:

https://github.com/opencv/opencv/blob/16928806f998a3112d52a086090833f54b65a3f1/modules/video/src/tracking/tracker_vit.cpp#L189-L197

**Comment by fengyuentau** [comment]
Please build the whole opencv library with your changes using `CMake` instead:

```
$ git clone https://github.com/opencv/opencv.git

# Apply your changes

$ cd opencv
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX=./install ..
$ cmake --build . --target install -j8

# Build complete

$ python3 -m pip install ./python_loader # this directory is under opencv/build
```
