### ISSUE TITLE
VitTracker weights (question)

### ISSUE THREAD

**Issue by arielkantorovich** [opencv/opencv_zoo#219]
Hi, I want to ask you about the weights `[object_tracking_vittrack_2023sep.onnx](https://github.com/opencv/opencv_zoo/blob/main/models/object_tracking_vittrack/object_tracking_vittrack_2023sep.onnx)` the VitTracker is implementation of the papper [Joint Feature Learning and Relation Modeling for Tracking: A One-Stream Framework](https://arxiv.org/abs/2203.11991)?
Do you train on your own data or do you take weights from the GitHub OSTrack and change to ONNX I am asking because I want to try maybe another weights.
Thank you for your help :)

**Comment by fengyuentau** [comment]
@lpylpy0514 Could you comment on this?

**Comment by lpylpy0514** [comment]
I used the same training dataset as OSTrack, but without using pre-trained weights. In terms of model implementation, I replaced patch embedding for small models. For this, please refer to [Levit: a vision transformer in convnet's clothing for faster inference](http://openaccess.thecvf.com/content/ICCV2021/html/Graham_LeViT_A_Vision_Transformer_in_ConvNets_Clothing_for_Faster_Inference_ICCV_2021_paper.html).

**Comment by arielkantorovich** [comment]
So If I want to check another weights option I can take the trained weights from OSTrack convert to onnx and just plug-in to opencv method?

**Comment by fengyuentau** [comment]
> I replaced patch embedding for small models.

@arielkantorovich There is model difference. You can still give it a try if you see that 1) model input shapes are matched and 2) number of outputs and output shapes are matched.

**Comment by arielkantorovich** [comment]
Hi,
VitTracker project support TensoRT models or only onnx models?

**Comment by fengyuentau** [comment]
OpenCV DNN does not support TensorRT models for now. So it works with the ONNX model that we provide. If you want to run this model on GPU with OpenCV DNN, you can try with the CUDA backend.

**Comment by shixiaokai306** [comment]
Hi, I want to ask you about the weights [object_tracking_vittrack_2023sep.onnx](https://github.com/opencv/opencv_zoo/blob/main/models/object_tracking_vittrack/object_tracking_vittrack_2023sep.onnx)
I want another onnx version weights, version：opset=11，
can you trans it for me？ Thank you for your help :)

**Comment by fengyuentau** [comment]
> Hi, I want to ask you about the weights [object_tracking_vittrack_2023sep.onnx](https://github.com/opencv/opencv_zoo/blob/main/models/object_tracking_vittrack/object_tracking_vittrack_2023sep.onnx) I want another onnx version weights, version：opset=11， can you trans it for me？ Thank you for your help :)

@shixiaokai306 Here is an example: https://github.com/fengyuentau/onnx_utils/blob/f94b6547037152abd3f48bdff3d8140749a1e12c/onnx_examples.py#L11-L24

**Comment by shixiaokai306** [comment]
@fengyuentau Hi, we can covert to 13, but cannot convert to 11, Below is the error info:
"RuntimeError: /github/workspace/onnx/version_converter/adapters/no_previous_version.h:23: adapt: Assertion `false` failed: No Previous Version of HardSwish exists"

**Comment by fengyuentau** [comment]
HardSwish is since ONNX opset >= 14. See https://github.com/onnx/onnx/blob/main/docs/Operators.md#version-72.

However, you can try modify the onnx graph to extract each HardSwish into Mul(x, HardSigmoid(x)) as the onnx documentation says:

> HardSwish function, y = x * max(0, min(1, alpha * x + beta)) = x * HardSigmoid<alpha, beta>(x)

HardSigmoid is since opset >= 1.

**Comment by superware** [comment]
> OpenCV DNN does not support TensorRT models for now. So it works with the ONNX model that we provide. If you want to run this model on GPU with OpenCV DNN, you can try with the CUDA backend.

Hello @fengyuentau, when I try `TrackerVit`'s `params.backend = 5;` and `params.target =  6;` (CUDA) on a Jetson Xavier NX with `OPENCV_LOG_LEVEL=DEBUG`, I'm getting:

```
[ INFO:0@16.313] global op_cuda.cpp:80 initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "_input" of type __NetInputLayer__
[ INFO:0@16.328] global op_cuda.cpp:80 initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "onnx_node!Reshape_77" of type Attention
[ INFO:0@16.329] global op_cuda.cpp:80 initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "onnx_node!Reshape_148" of type Attention
[ INFO:0@16.329] global op_cuda.cpp:80 initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "onnx_node!Reshape_219" of type Attention
```

And `tracker->update(...);` takes 40-80 ms which seems to indicate the model (or some of it?) is running on the CPU.

Any ideas?
