### ISSUE TITLE
Dynamic Input Shape?

### ISSUE THREAD

**Issue by ry-burke** [opencv/opencv_zoo#229]
I am using Rust & the ONNX Runtime (ort) crate to run the YuNet detection model which works fine with images resized to match the expected input shape of float32[1,3,640,640]. However, I was previously using YuNet via OpenCV where I could change the model input size per image at runtime which was very nice. Can you explain how that works in OpenCV even though the YuNet model has a fixed shape? I would like to try to recreate that functionality in Rust. Thank you.

**Comment by fengyuentau** [comment]
Everytime you run `net.setInput(input)`, dnn re-intializes the memory according to the input, so it works if the network is not shape-sensitive. You will need to export the ONNX model with dynamic shape if you want to achieve the same goal with ort.

**Comment by ry-burke** [comment]
Great, thanks for the quick response!
