### ISSUE TITLE
Lack of charsets in models\text_recognition_crnn

### ISSUE THREAD

**Issue by Aquapisces** [opencv/opencv_zoo#230]
according to models\text_recognition_crnn\README.md, there should be such files wich doesn't exist here:
![readme_charsets](https://github.com/opencv/opencv_zoo/assets/31422877/55841b77-4532-40a9-b295-41fa3c74a175)

and charset of 2022 and 2023 onnx are even not mentioned here. Would u please do supplementary uploads?  Thanks

**Comment by fengyuentau** [comment]
They are moved to https://github.com/opencv/opencv_zoo/blob/main/models/text_recognition_crnn/crnn.py already. Documentation is not up-to-date.

**Comment by Aquapisces** [comment]
> They are moved to https://github.com/opencv/opencv_zoo/blob/main/models/text_recognition_crnn/crnn.py already. Documentation is not up-to-date.

Thanks! What about "text_recognition_CRNN_CN_2021nov_int8.onnx"？This and some onnx else are mentioned neighter in README.md nor crnn.py

**Comment by fengyuentau** [comment]
*_int8.onnx are int8-quantized, same for *_fp16.onnx. They should work and produce results close to the original.

**Comment by Aquapisces** [comment]
> *_int8.onnx are int8-quantized, same for *_fp16.onnx. They should work and produce results close to the original.

But the recognize result of *_int8.onnx isn't the same with *.onnx. I got only ASCII characters instead of Chinese.

**Comment by fengyuentau** [comment]
It turns out those int8-quantized models loses accuracy. So better use the normal ones.

**Comment by Aquapisces** [comment]
> It turns out those int8-quantized models loses accuracy. So better use the normal ones.

谢谢啊，你回信都好及时，不像百度，PaddleOCR内存泄漏居然都没人发现也没人管，完全没法用

**Comment by fengyuentau** [comment]
谢谢，欢迎随时提出问题或者需求，我们会即时处理 ：）

**Comment by ChiragBindal** [comment]
In image_classification_mobilenet/demo.py
We can use threads so that they can work asyncronously
