### ISSUE TITLE
Is it possible to parallelize face detection process using the face_detection_yunet model in C++?

### ISSUE THREAD

**Issue by raulrguez09** [opencv/opencv_zoo#242]
I have been working with OpenCV in order to perform face detection tasks in C++, and I was wondering if it is possible to parallelize the face detection process using the Yunet model. My idea was to divide the frame in two parts and create a thread for each one. These threads would perform the detection task and write the results in a shared variable. Unfortunately, when I finished implementing my version I measured the time it takes to perform the detection and I found that it takes the same time as if I use a single thread.

This does not seem right because with 2 threads we are processing half of the pixels. So I wanted to ask whether or not it is possible to carry out this task, especially to find out if I have made a mistake in my implementation.

Thanks in advance.

**Comment by fengyuentau** [comment]
Cutting the image into halves is not a good approach, because you lose faces sitting on the cut line, which normally happens since people take pictures with face centered. The face detection itself in opencv has been parallelized. Two approaches you can try to improve efficiency:

- Run in batch, e.g. use `blobFromImages` in place of `blobFromImage`. This is not availble with integrated API `cv.FaceDetectorYN` though. But you can dig into the code to see how to do so.
- Shrink image size to 1/4, 1/3, 1/2 to see which gives the best results with sufficient speed. Larger image takes more time for face detection.

**Comment by raulrguez09** [comment]
Thanks for the quick reply! I know my idea was not the best approach but I’m using a embedded system (Quad-Core ARM 32 bits) and I was trying to figure out if I could perform face detection at real-time, or at least, as fast as possible. I already try the "reduce image size" option, but as I said, I was trying to know if there are other ways to improve efficiency.

As for the other option you gave me, I assume that using 'blobFromImages' allows you to add several images to the network input, and once you run the net.forward() function you can get the detection results for each of the input images, am I right?

Finally, do you know of any other face detection model or inference algorithm to achieve my goal (perform face detection at real-time) in the system I am using?

**Comment by fengyuentau** [comment]
> As for the other option you gave me, I assume that using 'blobFromImages' allows you to add several images to the network input, and once you run the net.forward() function you can get the detection results for each of the input images, am I right?

Yes.

> Finally, do you know of any other face detection model or inference algorithm to achieve my goal (perform face detection at real-time) in the system I am using?

YuNet has been one of the fastest face detection model. Question is whether you can find a inference framework that works the best on ARM-32bit platform. OpenCV might not be the best here.

**Comment by raulrguez09** [comment]
> Question is whether you can find a inference framework that works the best on ARM-32bit platform.

Do you have any recommendations? I've been searching but I've only found some python based and not C++ based ones, like this: [LFD](https://github.com/YonghaoHe/LFD-A-Light-and-Fast-Detector)

**Comment by fengyuentau** [comment]
Inference framework is something that takes any deep learning models and run inference. YuNet is one of the deep learning face detection models, as well as the one you mentioned. TFLite, ncnn, paddle-lite, mnn could also be your choice of inference frameworks.

**Comment by raulrguez09** [comment]
Okey, I'll investigate further to find a proper inference framework. Thank you very much for your help!
