### ISSUE TITLE
How to process output of face detection network when batch of images is used as network input?

### ISSUE THREAD

**Issue by raulrguez09** [opencv/opencv_zoo#244]
I have been working with OpenCV (4.8.0) in order to perform face detection tasks in C++. I was trying to process the detection with a batch of images using the 'blobFromImages' function, but i dont know how to process the output of the forward function. 

I know that the 'forward function' runs forward pass to compute outputs of layers and returns a list of ouput blobs. In my case, as I'm using the yunet model, the output_blobs variable should be a vector of Mat's with size equal to 12 (output_names = { "cls_8", "cls_16", "cls_32", "obj_8", "obj_16", "obj_32", "bbox_8", "bbox_16", "bbox_32", "kps_8", "kps_16", "kps_32" }). Also, I know that once you have the output_blobs variable, you can extract info related to the class probabilities, objectness scores, bounding box coordinates and keypoints, in order to paint the detected faces. I have already looked at the Yunet API code, to know how they extracted this information from the output_blobs variable:
         
    # Part of the postProcess function in 'face_detect.cpp' file
    for (size_t i = 0; i < strides.size(); ++i) {
        int cols = int(padW / strides[i]);
        int rows = int(padH / strides[i]);

        // Extract from output_blobs
        Mat cls = output_blobs[i];
        Mat obj = output_blobs[i + strides.size() * 1];
        Mat bbox = output_blobs[i + strides.size() * 2];
        Mat kps = output_blobs[i + strides.size() * 3];

        ( ... )
    }

But, how can I process the output_blobs to discern the faces detected in each of the images used as the input?

Thanks in advance.

**Comment by LaurentBerger** [comment]
No idea but try

        for (int i = 0; i < output_blobs.dims; i++)
            cout << output_blobs.size[i] << "\t";

to understand output  blob size

**Comment by fengyuentau** [comment]
Open `face_detection_yunet_2023mar.onnx` with netron, click on the input node, then you can see the following outputs:

![image](https://github.com/opencv/opencv_zoo/assets/17219438/8f0530f0-b919-41c9-8891-ce3a1492aee0)

They are all three dimensional, [1, x, n].

- The first dimension `1` is the batch. If you change the batch in your case, this will become the number of images you load with `blobFromImages`.
- The second dimension `x` is the number of instances. It stands for each batch has `x` instances.
- The last dimension `n` is the values. For example, `cls_8` has shape [1, 6400, 1] and it means it has one batch, each batch with 6400 instances and each instance have a probability saying how close the instance is a face. As for `bbox_`, the last dimension is saying each instance have the bounding box coordinates (x1, y1, w, h). Others follow.

**In your case, you just need to add a outer loop going through all instances in each batch**.

**Comment by raulrguez09** [comment]
Okey, thanks to your explanation I now understand the output of the forward function much better, but there's still one thing I don't get. I ran the following code in order to see the dimensions of the input and output blobs:

    Mat input_blob = cv::dnn::blobFromImages(imgArray);
    cout << "Input blob size: " << input_blob.size << endl;

    for (int i = 0; i < output_blobs.size(); i++)
        cout << output_blobs[i].size << "\t ";


And these are the outputs using one and two images as inputs:

![imagen](https://github.com/opencv/opencv_zoo/assets/44619080/1b18ffb8-41d8-4f53-946a-b481fdf165c2)

![imagen](https://github.com/opencv/opencv_zoo/assets/44619080/9e8a8636-852b-4a0d-8891-d78846314b83)

As you can see, in the second screenshot where I use two images as inputs, the first dimension ('the batch' as you said before) is 1. Taking into account what you said, I think the value should be 2 but I'm not sure. In the case of the second dimension (the number of instances) you can see that, by using two images, the number of instances is doubled.

> The second dimension x is the number of instances. It stands for each batch has x instances.

So, in my case, the total number of instances correspondig to each image is equal to: x total_instances / n number of images? And if so, all I have to do is add the outer loop and iterate through the corresponding instances for each image?

**Comment by LaurentBerger** [comment]
> for (int i = 0; i < output_blobs.size(); i++)
>     cout << output_blobs[i].size << "\t ";

You should use this code : 
```
for (int i = 0; i < output_blobs.dims; i++)
        cout << output_blobs.size[i] << "\t";
```
It will give you result  shape

**Comment by fengyuentau** [comment]
> Okey, thanks to your explanation I now understand the output of the forward function much better, but there's still one thing I don't get. I ran the following code in order to see the dimensions of the input and output blobs:
> 
> ```
> Mat input_blob = cv::dnn::blobFromImages(imgArray);
> cout << "Input blob size: " << input_blob.size << endl;
> 
> for (int i = 0; i < output_blobs.size(); i++)
>     cout << output_blobs[i].size << "\t ";
> ```
> 
> And these are the outputs using one and two images as inputs:
> 
> ![imagen](https://private-user-images.githubusercontent.com/44619080/312427130-1b18ffb8-41d8-4f53-946a-b481fdf165c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDAxMDIsIm5iZiI6MTcxMDMzOTgwMiwicGF0aCI6Ii80NDYxOTA4MC8zMTI0MjcxMzAtMWIxOGZmYjgtNDFkOC00ZjUzLTk0NmEtYjQ4MWZkZjE2NWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE0MjMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4OGExODFhNzI1Y2I3NGY1OWVlMDEwZGRkODZiNzdkZjllZWVmYTFlYjU5NDA2YTE3MTNjNzMxNDUzMDdkNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pdzV4NuBeZum-cEb_kL8_laLcDI5gCu6IDMq8Gic3j8)
> 
> ![imagen](https://private-user-images.githubusercontent.com/44619080/312425241-9e8a8636-852b-4a0d-8891-d78846314b83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDAxMDIsIm5iZiI6MTcxMDMzOTgwMiwicGF0aCI6Ii80NDYxOTA4MC8zMTI0MjUyNDEtOWU4YTg2MzYtODUyYi00YTBkLTg4OTEtZDc4ODQ2MzE0YjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE0MjMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MjhjZjlmNjFmYzBmNWRiMmY3YjBkNjM5ZGQwYTlmZWRkNzg3NmQ4MzgxOTM3NmM3MWVkZjljMjJhNGEzZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qbGUBbLUtzwJHkgS-IcpcH6PL9qVH5NgKSaq7jBZ-xo)
> 
> As you can see, in the second screenshot where I use two images as inputs, the first dimension ('the batch' as you said before) is 1. Taking into account what you said, I think the value should be 2 but I'm not sure. In the case of the second dimension (the number of instances) you can see that, by using two images, the number of instances is doubled.
> 
> > The second dimension x is the number of instances. It stands for each batch has x instances.
> 
> So, in my case, the total number of instances correspondig to each image is equal to: x total_instances / n number of images? And if so, all I have to do is add the outer loop and iterate through the corresponding instances for each image?

Okay, it turns out that Reshape operators set the batch to 1 and leave the inter-dimension to be inferred during inference. See below.

<img width="718" alt="image" src="https://github.com/opencv/opencv_zoo/assets/17219438/34364c46-48eb-4f80-a1ed-272ebddc732c">

Here `-1` stands for "to be inferred". Check https://github.com/onnx/onnx/blob/main/docs/Operators.md#Reshape for more information. You can use `Mat.reshape` to reshape, e.g. `a.reshape(1, std::vector<int>{2, 6400, 10})` if it has output shape [1, 12800, 10].

**Comment by raulrguez09** [comment]
Many thanks to both of you for your contributions. I was able to fix the issue by modifying the Yunet API code to iterate over the corresponding instances of each image (x total_instances / n number of images).

**Comment by fengyuentau** [comment]
Feel free to reopen issue if you come up with problems. Closing as the question is resolved.
