### ISSUE TITLE
I can't run the yunet_2023mar in OpenCV4.9.0

### ISSUE THREAD

**Issue by HuangTingXuanA** [opencv/opencv_zoo#252]
ubuntu22.04
gcc/g++ 10

My problem now is that the instruction:
Ptr<FaceDetectorYN> detector = FaceDetectorYN::create(yunet_modelPath, “”, Size(320, 320), 0.9, 0.3, 3000);
does not load the existing *.onnx file, but throws an exception.

OpenCV4.9.0 can't read ONNX when I use the yunet_2023mar.onnx in cpp.
what():  OpenCV(4.9.0) /opt/opencv-4.9.0/modules/dnn/src/onnx/onnx_importer.cpp:275: error: (-5:Bad argument)

**Comment by fengyuentau** [comment]
Duplicate of https://github.com/opencv/opencv_zoo/issues/93.

Check whether your models are cloned with git-lfs correctly.

**Comment by HuangTingXuanA** [comment]
@fengyuentau Thanks for your reply. I have fixed the problem by following your method.
