### ISSUE TITLE
Face Anti-Spoofing opencv

### ISSUE THREAD

**Issue by raulrguez09** [opencv/opencv_zoo#253]
I have been working with OpenCV (4.8.0) in order to perform face recognition tasks in C++. I followed this [tutorial](https://docs.opencv.org/4.x/d0/dd4/tutorial_dnn_face.html) and used the sface model listed in this repository. When I ran tests to see if the sface model could cope with spoofing attacks, I found that it could not deal with such attacks. Does OpenCV provide any method to deal with spoofing attacks? or do i need to use another deep learning based model prepare for face anti-spoofing?

Thanks in advance.

**Comment by fengyuentau** [comment]
SFace is for face recognition without handling spoofing attacks. That's why you can see the demo can tell whether persons from two different images are the same identity or not. AFAIK, OpenCV does not provide out-of-the-box face anti-spoofing methods. You need to go on your way finding one.
