### ISSUE TITLE
总是报错 

### ISSUE THREAD

**Issue by fox007ggr** [opencv/opencv_zoo#254]
cv2.error: OpenCV(4.9.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:280: error: (-210:Unsupported format or combination of formats) Failed to parse ONNX model: object_detection_yolox_2022nov.onnx in function 'ONNXImporter'

**Comment by fengyuentau** [comment]
安装git-lfs，然后再clone本仓库，参考[readme](https://github.com/opencv/opencv_zoo?tab=readme-ov-file#opencv-zoo-and-benchmark)：

```
# Install git-lfs from https://git-lfs.github.com/
git clone https://github.com/opencv/opencv_zoo && cd opencv_zoo
git lfs install
git lfs pull
```
