### ISSUE TITLE
the issue of quantification

### ISSUE THREAD

**Issue by zhaoyangwei123** [opencv/opencv_zoo#262]
[face_detection_yunet_2023mar_int8.onnx](https://github.com/opencv/opencv_zoo/blob/4.9.0/models/face_detection_yunet/face_detection_yunet_2023mar_int8.onnx)
I would like to ask if this onnx is statically quantified to int8, and is it exported using the pth file of pytorch?

**Comment by fengyuentau** [comment]
The original model (fp32) is trained on MXNet, then it was converted to ONNX, and quantized with https://github.com/opencv/opencv_zoo/tree/main/tools/quantize.
