### ISSUE TITLE
Failed to run with `python benchmark.py --cfg ./config/face_detection_yunet.yaml`

### ISSUE THREAD

**Issue by ddwolf** [opencv/opencv_zoo#281]
Here is the output of the command
```
[xxx@fedora-riscv benchmark]$ python benchmark.py --cfg ./config/face_detection_yunet.yaml
Benchmarking ...
mean       median     min        input size   model
12.16      12.25      11.91      [160, 120]   YuNet with ['face_detection_yunet_2023mar.onnx']
11.73      11.83      11.22      [160, 120]   YuNet with ['face_detection_yunet_2023mar_int8.onnx']
[ERROR:0@3.470] global onnx_importer.cpp:1035 handleNode DNN/ONNX: ERROR during processing node with 3 inputs and 1 outputs: [DequantizeLinear]:(onnx_node!bbox_head.multi_level_kps.2.conv2.weight_quantized_node) from domain='ai.onnx'
Traceback (most recent call last):
  File "/home/xxx/repos/opencv_zoo/benchmark/benchmark.py", line 226, in <module>
    model = model_handler(*model_path, **model_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/repos/opencv_zoo/models/face_detection_yunet/yunet.py", line 22, in __init__
    self._model = cv.FaceDetectorYN.create(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.10.0) /tmp/pip-install-uvko15ge/opencv-python_5d2ac5030ab94a15b5dcfd252013fa45/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1057: error: (-2:Unspecified error) in function 'handleNode'
> Node [DequantizeLinear@ai.onnx]:(onnx_node!bbox_head.multi_level_kps.2.conv2.weight_quantized_node) parse error: OpenCV(4.10.0) /tmp/pip-install-uvko15ge/opencv-python_5d2ac5030ab94a15b5dcfd252013fa45/opencv/modules/dnn/src/int8layers/quantization_utils.cpp:18: error: (-215:Assertion failed) axis >= 0 && targetShape.size() > axis && data.total() == targetShape[axis] in function 'broadcast1D2TargetMat'
>
```

**Comment by fengyuentau** [comment]
> cv2.error: OpenCV(4.10.0)

Hello @ddwolf , OpenCV 4.x does not support block quantized models, which are models with suffix `int8bq`. If you stick with 4.x, you could use filters run others without block quantized models, e.g. `python3 benchmark.py --fp32 --int8`.

**Comment by ddwolf** [comment]
> > cv2.error: OpenCV(4.10.0)
> 
> Hello @ddwolf , OpenCV 4.x does not support block quantized models, which are models with suffix `int8bq`. If you stick with 4.x, you could use filters run others without block quantized models, e.g. `python3 benchmark.py --fp32 --int8`.

Thanks for your reply, I'll take a try later.

**Comment by ddwolf** [comment]
![image](https://github.com/user-attachments/assets/26e166aa-7d46-4c9f-9b90-6f141eebce2c)

By the way, could you please tell me, among the  three numbers: mean, median, min, what number do you use to fill into this image?

![image](https://github.com/opencv/opencv_zoo/raw/main/benchmark/color_table.svg?raw=true)

**Comment by fengyuentau** [comment]
> After dozens of cases, it complains module cv2 has no attribute wechat_qrcode_WeChatQRCode

It is in `opencv-contrib-python`, you can either exclude it or install the package along with `opencv-python`.

**Comment by ddwolf** [comment]
Thank you so much, @fengyuentau, issue solved.
