### ISSUE TITLE
face_detection_yunet

### ISSUE THREAD

**Issue by donaldlee2008** [opencv/opencv_zoo#31]
os:windows
python: 3.6
opecv-python:4.5.4
face_detection_yunet/demo.py   
cmd: python demo.py   -i 3.jpg
error:
onnx_importer.cpp:203: error: (-210:Unsupported format or combination of formats) Failed to parse ONNX model: face_detection_yunet_2021sep.onnx in function 'cv::dnn::dnn4_v20211004::ONNXImporter::ONNXImporter'

**Comment by fengyuentau** [comment]
Did you test on WIndows CMD or WSL?

**Comment by donaldlee2008** [comment]
> Did you test on WIndows CMD or WSL?

WIndows CMD

**Comment by donaldlee2008** [comment]
It works when I download the model from 
https://github.com/ShiqiYu/libfacedetection.train/blob/a61a428929148171b488f024b5d6774f93cdbc13/tasks/task1/onnx/yunet.onnx   
but face_detection_yunet_2021sep.onnx does not

**Comment by bwmcin** [comment]
Opened face_detection_yunet_2022mar.onnx in notepad+ and got this...

version https://git-lfs.github.com/spec/v1
oid sha256:50ef07f702a31741ca46a4c0d947773b64143b9362780237bf0d427d6c79bab7
size 345478

....and nothing else.  Also, the file size is very small.

face_detection_yunet_2022_mar-act_int8-wt_int8-quantized.onnx has similar issue.

**Comment by fengyuentau** [comment]
@bwmcin You need to install git-lfs from https://git-lfs.github.com/ and run 
```shell
cd your/opencv_zoo
git lfs install
git pull
```
Or clone a fresh copy of opencv_zoo after you install git-lfs:
```shell
git lfs install
git clone https://github.com/opencv/opencv_zoo
```

**Comment by zihaomu** [comment]
Hi @donaldlee2008, does `git lfs install` solve your problem?

**Comment by deepti-pushpak** [comment]
cv2.error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:260: error: (-210:Unsupported format or combination of formats) Failed to parse ONNX model: face_detection_yunet_2022mar.onnx in function 'ONNXImporter'

I am having the same problem on my ubuntu 20.04.4. Could anyone resolve this?

**Comment by fengyuentau** [comment]
@deepti-pushpak Follow the instructions in [README](https://github.com/opencv/opencv_zoo/blob/master/README.md) to install git-lfs to pull models.

**Comment by deepti-pushpak** [comment]
> @deepti-pushpak Follow the instructions in [README](https://github.com/opencv/opencv_zoo/blob/master/README.md) to install git-lfs to pull models.

@fengyuentau I can't thank you enough. Your suggestion works! I am able to run the detection code now that utilizes onnx. Thank you for saving me tons of work.

**Comment by Radeeshp** [comment]
I am not able to run this line :
    detector = cv2.FaceDetectorYN.create("face_detection_yunet_2023mar.onnx", "", (640, 480))
 i have tried it with others files too. 
This is the error i get when i try to run this line



[ WARN:0@1.646] global loadsave.cpp:244 cv::findDecoder imread_('face_detection_yunet_2023mar.onnx'): can't open/read file: check file path/integrity
Error: Unable to open file.
Traceback (most recent call last):
  File "f:\EDUCATION\PROJECTS\FACE DETECTION\Face_detection_Yunet\Yunet_Code.py", line 21, in <module>
    detector = cv2.FaceDetectorYN.create("face_detection_yunet_2023mar.onnx", "", (640, 480))
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:270: error: (-5:Bad argument) Can't read ONNX file: face_detection_yunet_2023mar.onnx in function 'cv::dnn::dnn4_v20221220::ONNXImporter::ONNXImporter'

**Comment by JefferyChia** [comment]
I follow the instructions in [README](https://github.com/opencv/opencv_zoo/blob/master/README.md) to install git-lfs to pull models and re-run my model. However, the error still persists.

cv2.error: OpenCV(4.8.1) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:279: error: (-210:Unsupported format or combination of formats) Failed to parse ONNX model: face_detection_yunet_2023mar.onnx in function 'ONNXImporter'

onnx model: face_detection_yunet_2023mar.onnx

can someone help?

**Comment by fengyuentau** [comment]
@JefferyChia Please doublecheck whether you correctly installed git-lfs and pulled the models with the following commands:

```shell
$ git lfs status
```

It prints `git: 'lfs' is not a git command. See 'git --help'.` if git-lfs is not installed.

```shell
$ echo "8f2383e4dd3cfbb4553ea8718107fc0423210dc964f9f4280604804ed2552fa4  face_detection_yunet_2023mar.onnx" | shasum -a 256 -c
```

It prints `OK` if `face_detection_yunet_2023mar.onnx` is pulled correctly.

**Comment by JefferyChia** [comment]
@fengyuentau I checked the status of git-lfs and the output is this:

> On branch main
> Git LFS objects to be pushed to origin/main:
> 
> 
> Git LFS objects to be committed:
> 
> 
> Git LFS objects not staged for commit:

However, I got an error when I type in the echo command:

> shasum: face_detection_yunet_2023mar.onnx: No such file or directory
> face_detection_yunet_2023mar.onnx: FAILED open or read
> shasum: WARNING: 1 listed file could not be read

Can you help me?

**Comment by fengyuentau** [comment]
You need to run demo and my commands in `models/face_detection_yunet`.

**Comment by JefferyChia** [comment]
@fengyuentau I ran the demo.py but the error still persists.

> Traceback (most recent call last):
>   File "/media/ntnuvip/HardDisk/Jeffery/opencv_zoo/models/face_detection_yunet/demo.py", line 83, in <module>
>     model = YuNet(modelPath=args.model,
>   File "/media/ntnuvip/HardDisk/Jeffery/opencv_zoo/models/face_detection_yunet/yunet.py", line 22, in __init__
>     self._model = cv.FaceDetectorYN.create(
> cv2.error: OpenCV(4.8.1) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:279: error: (-210:Unsupported format or combination of formats) Failed to parse ONNX model: face_detection_yunet_2023mar.onnx in function 'ONNXImporter'

**Comment by JefferyChia** [comment]
Hey @fengyuentau, I think it runs well. However, now I have a new error:

> Traceback (most recent call last):
>   File "demo.py", line 101, in <module>
>     print('{} faces detected.'.format(results.shape[0]))
> AttributeError: 'NoneType' object has no attribute 'shape' 

Is there an issue on this?

**Comment by fengyuentau** [comment]
That means no faces are detected. It returns none in this case.

**Comment by JefferyChia** [comment]
@fengyuentau my input is a face, however, I am not sure why the error persists. Do I need to reshape the size of the image or is it unnecessary?

`python3 demo.py -i human_faces.jpg`

![Human_faces](https://github.com/opencv/opencv_zoo/assets/123931719/39473d37-8b8b-4a6f-9411-843eed167adf)

**Comment by fengyuentau** [comment]
These faces are way too big to be able to be detected by this model. Try to shrink this image to 1/4 of its original size and I can get the follow result,

![result](https://github.com/opencv/opencv_zoo/assets/17219438/7fdcb153-23cd-48e9-8e5c-177de0467e3b)
