### ISSUE TITLE
Is it possible for Lama to integrate into opencvzoo in the future

### ISSUE THREAD

**Issue by jsxyhelu** [opencv/opencv_zoo#32]
LaMa: Resolution-robust Large Mask Inpainting with Fourier Convolutions
is a great inpating model (https://github.com/saic-mdal/lama)
Is it possible for Lama to integrate into opencvzoo in the future?

**Comment by fengyuentau** [comment]
Can you provide more information like this issue https://github.com/opencv/opencv_zoo/issues/19?
