### ISSUE TITLE
Inference Yunet and SFace with GPU or TensorRT?

### ISSUE THREAD

**Issue by hmh10098** [opencv/opencv_zoo#40]
Hi, can you help me, how to inference Yunet and Sface.onnx with GPU?

**Comment by fengyuentau** [comment]
1. Compile OpenCV with CUDA. Following is the CMake command I used, you will have to fit it in your case:
    ```shell
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
     -D CMAKE_INSTALL_PREFIX=./install \
     -D BUILD_opencv_python2=OFF \
     -D BUILD_opencv_python3=ON \
     -D PYTHON3_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.6m.so \
     -D PYTHON3_INCLUDE_DIR=/usr/include/python3.6m \
     -D PYTHON3_EXECUTABLE=/usr/bin/python3.6 \
     -D WITH_CUDA=ON \
     -D WITH_CUDNN=ON \
     -D OPENCV_DNN_CUDA=ON \
     -D CUDA_FAST_MATH=ON \
     -D ENABLE_FAST_MATH=1 \
     -D CUDA_ARCH_BIN=5.3 \
     -D WITH_CUBLAS=1 \
     -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.2 \
     -D OPENCV_EXTRA_MODULES_PATH=/home/opencv-cn/Workspace/opencv/opencv_contrib/modules  ..
    ```
    You can find your CUDA_ARCH_BIN at https://developer.nvidia.com/cuda-gpus (compute capability in the tables).
2. Initialize YuNet & SFace with CUDA backend and GPU target in demo scripts:
    ```python
    yunet = YuNet(modelPath=args.model_yunet, backendId=cv.dnn.DNN_BACKEND_CUDA, targetId=cv.dnn.DNN_TARGET_CUDA)
    sface = SFace(modelPath=args.model_sface, backendId=backendId=cv.dnn.DNN_BACKEND_CUDA, targetId=cv.dnn.DNN_TARGET_CUDA)
    ````

And you can run demo scripts and perform inference of YuNet & SFace on GPU.

**Comment by hmh10098** [comment]
> 1. Compile OpenCV with CUDA. Following is the CMake command I used, you will have to fit it in your case:
>    ```shell
>    cmake -D CMAKE_BUILD_TYPE=RELEASE \
>     -D CMAKE_INSTALL_PREFIX=./install \
>     -D BUILD_opencv_python2=OFF \
>     -D BUILD_opencv_python3=ON \
>     -D PYTHON3_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.6m.so \
>     -D PYTHON3_INCLUDE_DIR=/usr/include/python3.6m \
>     -D PYTHON3_EXECUTABLE=/usr/bin/python3.6 \
>     -D WITH_CUDA=ON \
>     -D WITH_CUDNN=ON \
>     -D OPENCV_DNN_CUDA=ON \
>     -D CUDA_FAST_MATH=ON \
>     -D ENABLE_FAST_MATH=1 \
>     -D CUDA_ARCH_BIN=5.3 \
>     -D WITH_CUBLAS=1 \
>     -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.2 \
>     -D OPENCV_EXTRA_MODULES_PATH=/home/opencv-cn/Workspace/opencv/opencv_contrib/modules  ..
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    You can find your CUDA_ARCH_BIN at https://developer.nvidia.com/cuda-gpus (compute capability in the tables).
> 2. Initialize YuNet & SFace with CUDA backend and GPU target in demo scripts:
>    ```python
>    yunet = YuNet(modelPath=args.model_yunet, backendId=cv.dnn.DNN_BACKEND_CUDA, targetId=cv.dnn.DNN_TARGET_CUDA)
>    sface = SFace(modelPath=args.model_sface, backendId=backendId=cv.dnn.DNN_BACKEND_CUDA, targetId=cv.dnn.DNN_TARGET_CUDA)
>    ```
> 
> And you can run demo scripts and perform inference of YuNet & SFace on GPU.

thanks for your help!

**Comment by sayyid-abolfazl** [comment]
Hello OpenCV Developers,

First, I want to thank you for this outstanding project. OpenCiV is the best

I’m working with models like YuNet, eDifFIQA(T), and SFace, and I’d like to deploy them on a Jetson device with CUDA and NVIDIA TensorRT to maximize speed and efficiency.

I successfully converted these models to TensorRT format using trtexec, but I need guidance on how to load and use them effectively in C++. Specifically:

    Could you provide any examples or best practices on using nvinfer1::ICudaEngine* engine = runtime->deserializeCudaEngine(buffer.data(), size, nullptr); to load these TensorRT models?

    Are there any recommended approaches, classes, or functions in OpenCV to help integrate these models with TensorRT in C++ on a Jetson device?

    Additionally, has anyone tested these specific models on Jetson in this setup to evaluate speed and accuracy improvements? I would love to hear about any performance insights or adjustments that could help.

    Lastly, would it be possible to integrate CUDA code into the project directly, similar to what YOLO models from Ultralytics have done?

Thank you for your time and support.

**Comment by fengyuentau** [comment]
@sayyid-abolfazl Models and demos in this repo are intended to work with OpenCV. Of course you can try with other inference frameworks, e.g. TensorRT. You will need to look for TensorRT examples elsewhere.
