### ISSUE TITLE
SFace image input should be RGB instead BGR?

### ISSUE THREAD

**Issue by rodrigo2019** [opencv/opencv_zoo#53]
Hello, I'm testing the Sface implementation and in my tests I need to set a higher cosine distance instead the default one (I'm using 0.463 instead 0.363) because I was getting too much false positives. I started to explore why this could happening and I checked  in the training script the author was using the [mxnet library for reading the samples](https://github.com/zhongyy/SFace/blob/main/SFace_torch/image_iter_rec.py#L69) and accordingly with the [mxnet documentation](https://mxnet.apache.org/versions/1.6/api/python/docs/api/mxnet/image/index.html#mxnet.image.imdecode) the default imdecode behavior is to load the image in the RGB format.
In the demo example, the images were read using [BGR format](https://github.com/opencv/opencv_zoo/blob/master/models/face_recognition_sface/demo.py#L62)
After feeding the Sface model with RGB images I started to get lower cosine distances that match with the standard threshold.

So it could be a mistake when the demo was wrote? Or I'm missing some step?

**Comment by rodrigo2019** [comment]
but it does [here](https://github.com/opencv/opencv/blob/4.x/modules/objdetect/src/face_recognize.cpp#L45)

**Comment by fengyuentau** [comment]
Hello @rodrigo2019 , thanks for finding the bug! Would you like to make a pull request for this?

**Comment by rodrigo2019** [comment]
Sure, I will be glab for helping.
But I'm not so sure if there is a bug, I read the C++ code and i saw that the cv2.blobfromimage is converting it to RGB, you can see [here](https://github.com/opencv/opencv/blob/4.x/modules/objdetect/src/face_recognize.cpp#L45)
so everything is happening from the c++ side, making the python side correct. Looks like it was my missunderstanding, probably my problem with the threshold is correlated with another situation that I didn't figured it out yet.

Do you confirm my premises?

**Comment by fengyuentau** [comment]
I doublechecked the cosine threshold used in OpenCV C++ [samples](https://github.com/opencv/opencv/blob/c8228e5789510ec26378eceb17311dd7bddf0b33/samples/dnn/face_detect.cpp#L70-L71) and [unit tests](https://github.com/opencv/opencv/blob/c8228e5789510ec26378eceb17311dd7bddf0b33/modules/objdetect/test/test_face.cpp#L155-L156). It turns out the default threshold (0.363) set in this repo is correct. Also the BGR2RGB convertion is done in the API so we do not need to convert it ourselves. Could you share some code and data so that I can reproduce your problem?

**Comment by rodrigo2019** [comment]
It's delicated to share the data, because of the lgpd stuff. I will try to reproduce with some open data and bring it to you. 
As the problem doesn't look to be the channel order I think we could close this issue.

Thank you for your help and time

**Comment by fengyuentau** [comment]
Okay, feel free to reopen this issue or open another one if you find the problem.
