### ISSUE TITLE
SFace validation

### ISSUE THREAD

**Issue by rodrigo2019** [opencv/opencv_zoo#54]
Hello I'm using the SFace implementation and my problem is that I need to use a much higher threshold (cosine distance) to it work properly. In my experiments I need to use something above 0.55 to get some reasonable results

I tried to make a very straight forward script for the validation. you can check it here: [https://github.com/rodrigo2019/sface_validation/blob/master/validation.ipynb](https://github.com/rodrigo2019/sface_validation/blob/master/validation.ipynb)

First I thought that the problem was my data, but after some tests even with datasets like LFW and using or not tools like face align I keep having high score for different persons

**Comment by fengyuentau** [comment]
Hello @rodrigo2019 , can you try without yunet? Yunet is used to find face location and landmarks for alignment, but the data you used is pre-aligned.

@crywang could you take a look at this problem?

**Comment by rodrigo2019** [comment]
I tried with both ways

**Comment by crywang** [comment]
In your code, "We suppose that there are only picture for each person". Actually, there may be several images with the same identity in LFW. Read [here](http://vis-www.cs.umass.edu/lfw/README.txt) for more details.

**Comment by rodrigo2019** [comment]
@crywang I saw it, but I'm getting a single picture per folder. I also know that even getting a single image per folder I can find the same picture in another folder, but it's not so common.

Look at this test, without using the YuNet for cropping the face, the sample index 2926 had 4956 matches with the cosine similarity above 0.363. 4956 matches means 86.22% of the entirely dataset
in the image you can see some of the matches with the cosine similarity wrote in the image
![image](https://user-images.githubusercontent.com/8016520/168630598-8cf05d7d-a966-4d18-9f34-458ec3b41d84.png)

**Comment by crywang** [comment]
You can do evaluation on our pre-aligned LFW dataset. [here](https://drive.google.com/file/d/1r7OzlgaEj17G-n_FQaKgqIiutROnckC_/view?usp=sharing)

**Comment by rodrigo2019** [comment]
@crywang thank you for sharing. I did the validation using [this script](https://github.com/rodrigo2019/sface_validation/blob/master/fine_tuning.ipynb)
I got close results than yours, I found 0.3789 for cosine and a bit higher value if I apply the YuNet (Around 0.4)

Thank you for helping me
