### ISSUE TITLE
Implementing multi-task CV models（GsoC-22)

### ISSUE THREAD

**Issue by obtx** [opencv/opencv_zoo#63]
## Abstract
Multi-task learning (MTL) is a branch of machine learning, in which multiple tasks learn simultaneously through a shared model. It has the following advantages: improving data efficiency, reducing overfitting through shared representation, and using auxiliary information to learn quickly.
At present, the implementation of the multi-task CV model is not in OpenCV, so developers based on OpenCV cannot use the multi-task model to reduce the amount of computation and improve the accuracy. 

>**Aim**: One or more multi-task CV models trained (or borrowed, if the license is appropriate), and submitted to OpenCV model zoo.

**Comment by puneeth072003** [comment]
@obtx Happy to help.
